### ISSUE TITLE
Busses do not function properly without additional middleware

### ISSUE THREAD

**Issue by geekish** [PHPMessageBus/messagebus#3]
I'm testing out this library in a project of mine. I was having problems with QueryBus returning an EmtpyResponse no matter what I did, but after looking at the code it seems that adding middleware in addition to QueryBusMiddleware causes it to function properly and return the correct response.

I haven't tested the other busses yet, but it looks like they all use `$current = array_shift($middleware);`, which, if you're only using the "core" middleware and nothing else, empties `$middleware` and the following `foreach` does not run.

Did I miss something in the docs or is this not the intention?

**Comment by nilportugues** [comment]
@geekish thanks for opening a question. Actually it's intentional. 

The QueryBus by itself won't do anything, it requires of one middleware returning a response. On the CommandBus and EventBus this won't happen as they are not returning data, but they require middleware to trully handle the message.

So, in your case, using a QueryBusMiddleware or a class implementing the interface at some point during the QueryBus handling is required and must be provided. 

If no middleware is provided an EmptyResponse is returned. Someone has to return a QueryResponse at some point to compile with the interface, and if so it will replace the EmptyResponse. 

Benefits on not enforcing having a mandatory middleware allows: 
- Overriding the default provided QueryBusMiddleware
- Create custom middlewares after the QueryBusMiddleware is ran, for instance mutating a QueryResponse (by creating a new one) that adds debug data if in development environment.

Hopefully I was clear and I could help you out.

Any recommendations in making the docs better? :)

**Comment by geekish** [comment]
I am indeed using QueryBusMiddleware, but in order to get a non-EmptyResponse I had to add another middleware to QueryBus, in this case LoggerQueryBusMiddleware with Psr\Log\NullLogger.

**Comment by nilportugues** [comment]
Hmm i'll write a test. Thanks  @geekish. Keep you posted.

**Comment by nilportugues** [comment]
@geekish I confirm it's a bug. Fixing it...

**Comment by nilportugues** [comment]
@geekish https://github.com/PHPMessageBus/messagebus/releases/tag/1.0.1
